customer/urls.py
from django.urls import path
from . import views

app_name = "customer"
urlpatterns = [
    path("", views.get_home_page, name="home_page"),

    path('signup/', views.signup, name='signup'),

    path('login/', views.custom_login, name='login'),

    path('logout/', views.custom_logout, name='logout'),

    path('profile/', views.view_profile, name='view_profile'),

    path('service_locations/', views.service_locations, name='service_locations'),

    path('detail_sl/', views.detailed_service_locations, name='detailed_service_locations'),

    path('add_service_location/', views.add_service_location, name='add_service_location'),

    path('delete_service_location/<int:location_id>/',
         views.delete_service_location, name='delete_service_location'),

    path('random_chart/', views.get_random_chart, name='random_chart'),

    path('delete_profile/', views.milestone_profile, name="milestone_profile"),

    path('edit_profile/', views.edit_profile, name='edit_profile'),

    path('edit_sl/<int:location_id>/', views.update_service_location, name="update_service_location"),
]

device/urls.py
from django.urls import path
from . import views

app_name = "device"
urlpatterns = [
    path('<int:device_id>/show_device_eusage/', views.show_device_eusage, name='show_device_eusage'),

    path('add_device/<int:location_id>/', views.add_device, name='add_device'),

    path('delete_device/<int:device_id>/', views.delete_device, name='delete_device'),

    path('show_user_eusage/', views.show_user_eusage, name='show_user_eusage'),

    path('show_sl_eusage/<int:location_id>/', views.show_service_location_eusage, name='show_sl_eusage'),

    path('get_devices/<int:location_id>/', views.get_devices, name='get_devices'),

    path('get_device_pie/<int:location_id>/', views.get_device_pie, name="get_device_pie"),

    path('get_prices/', views.get_prices, name='get_prices'),
]

smart_home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("customer.urls")),
    path('', include("device.urls")),
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MinLengthValidator


class ServiceLocation(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    apt_unit = models.IntegerField(
        default=1,
        verbose_name='AptUnit',
        help_text='Enter the Apartment unit of the building',
        validators=[MinValueValidator(1)],
    )
    street = models.CharField(
        max_length=50,
        verbose_name='Street Name',
        null=False,
    )
    state = models.CharField(
        max_length=20,
        verbose_name='State Name',
        null=False,
    )
    zipcode = models.CharField(
        default='00000',
        verbose_name='ZipCode',
        help_text='Enter the zipcode',
        validators=[MinLengthValidator(5)],
        null=False,
    )
    apt_name = models.CharField(
        max_length=100,
        verbose_name='AptName',
    )
    move_in_date = models.DateField(
        verbose_name='MoveInDate',
    )
    area = models.IntegerField(
        null=False,
        verbose_name='SquareFootage',
        validators=[MinValueValidator(100)],
    )
    bedroom = models.IntegerField(
        default=1,
        verbose_name='No of bedrooms',
        validators=[MinValueValidator(1)],
    )
    occupants = models.IntegerField(
        verbose_name='No of occupants',
    )
    is_active = models.BooleanField(
        default=True
    )

    def __str__(self):
        return f'{self.street}_{self.zipcode}_{self.state}_{self.id}'

customer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import ServiceLocation


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Please enter a valid email address.')

    class Meta:
        model = User
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
        }
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')


class DateInput(forms.DateInput):
    input_type = 'date'


class ServiceLocationForm(forms.ModelForm):
    class Meta:
        model = ServiceLocation
        fields = ['apt_unit', 'street', 'state', 'zipcode', 'apt_name', 'move_in_date',
                  'area', 'bedroom', 'occupants']
        widgets = {
            'move_in_date': DateInput(),
        }


class ServiceLocationUpdateForm(forms.ModelForm):

    class Meta:
        model = ServiceLocation
        fields = ['apt_unit', 'street', 'apt_name', 'move_in_date',
                  'area', 'bedroom', 'occupants']
        widgets = {
            'move_in_date': DateInput(),
        }


class ProfileEditForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class EnergyUsageForm(forms.Form):
    start_date = forms.DateField(
        label='Start Date',
        widget=DateInput()
    )
    end_date = forms.DateField(
        label='End Date',
        widget=DateInput()
    )
    cumulative = forms.BooleanField(
        label='Cumulative',
        required=False
    )

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        if start_date > end_date:
            raise forms.ValidationError('Start date cannot be greater than End date')

        return cleaned_data

    class Meta:
        fields = ['start_date', 'end_date', 'cumulative']
        widgets = {
            'cumulative': forms.CheckboxInput(attrs={
                'class': 'form-check-input'
            })
        }


CHOICES = [
    ('11213', '11213'),
    ('08619', '08619'),
]


class ZipCodePrice(forms.Form):
    zipcode = forms.ChoiceField(choices=CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    start_date = forms.DateField(
        label='Start Date',
        widget=DateInput()
    )
    end_date = forms.DateField(
        label='End Date',
        widget=DateInput()
    )
    cumulative = forms.BooleanField(
        label='Cumulative',
        required=False
    )

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        if start_date >= end_date:
            raise forms.ValidationError('Start date cannot be greater than equal to end date')

        return cleaned_data

    class Meta:
        fields = ['start_date', 'end_date', 'cumulative']
        widgets = {
            'cumulative': forms.CheckboxInput(attrs={
                'class': 'form-check-input'
            })
        }

customer/views.py
from django.shortcuts import get_object_or_404
import random

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import SignUpForm, ServiceLocationForm, ProfileEditForm, ServiceLocationUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import ServiceLocation
from django.urls import reverse


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.email = form.cleaned_data.get('email')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            messages.success(request, "Successfully signed up and logged you in!")
            return redirect('customer:home_page')
    else:
        form = SignUpForm()
    return render(request, 'customer/signup.html', {'form': form})


def custom_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.raw('SELECT * FROM auth_user WHERE username = %s', [username])

        if len(user):
            user = user[0]
        else:
            messages.error(request, "No account found with that username. Please register.")
            return redirect('customer:home_page')

        if user is not None:
            if not user.is_active:
                messages.error(request, "Your account is inactive.")
                return redirect('customer:login')

            if not user.check_password(password):
                messages.error(request, "Incorrect Password! Please try again. ")
                return redirect('customer:login')

            user = authenticate(request, username=username, password=password)
            if user.is_active:
                login(request, user)
                messages.success(request, "You have successfully logged in")
                return redirect('customer:home_page')
        else:
            messages.error(request, "Invalid username or password.")

    return render(request, 'customer/login.html')


@login_required
def custom_logout(request):
    logout(request)
    messages.success(request, "You have successfully logged out.")
    return redirect('customer:login')


def get_home_page(request):
    return render(request, 'customer/home.html', {})


@login_required
def view_profile(request):
    context = {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
        'email': request.user.email
    }
    return render(request, 'customer/profile_view.html', context)


@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        profile_form = ProfileEditForm(request.POST, instance=user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, "Profile successfully updated.")
            return redirect(reverse('customer:view_profile'))
    else:
        profile_form = ProfileEditForm(instance=user)
    return render(request, 'customer/edit_profile.html', context={'form': profile_form})


@login_required
def milestone_profile(request):
    if request.method == 'POST':
        try:
            current_user = User.objects.raw('SELECT * FROM auth_user WHERE id = %s', [request.user.id])[0]
            if current_user.is_active:
                current_user.is_active = False
                current_user.save()
                logout(request)
                messages.success(request, "Successfully deleted your profile!")
            return redirect(reverse('customer:home_page'))
        except Exception as e:
            print(e)
    return render(request, 'customer/delete_profile.html')


# ============================ SERVICE LOCATION IMPLEMENTATION ======================================


@login_required
def service_locations(request):
    sql_query = (
        f"SELECT * FROM customer_servicelocation "
        f"WHERE user_id = {request.user.id} AND is_active = 't'"
    )
    locations = ServiceLocation.objects.raw(sql_query)
    return render(request, 'customer/view_locations.html', {'locations': locations})


@login_required
def detailed_service_locations(request):
    location_id = request.POST.get('location_id')
    sql_query = (f"SELECT * from customer_servicelocation "
                 f"WHERE id = {location_id}")
    locations = ServiceLocation.objects.raw(sql_query)
    if len(locations) == 0:
        return redirect(reverse('customer:service_locations'))
    location = locations[0]
    return render(request, 'customer/service_locations.html', {'location': location})


@login_required
def add_service_location(request):
    form = ServiceLocationForm(request.POST)
    if form.is_valid():
        service_location = form.save(commit=False)
        service_location.user = request.user
        service_location.save()
        return redirect('customer:service_locations')
    else:
        form = ServiceLocationForm()
    return render(request, 'customer/add_service_location.html', {'form': form})


@login_required
def update_service_location(request, location_id):
    sl_instance = ServiceLocation.objects.raw(
        f"SELECT * from customer_servicelocation WHERE id = {location_id}"
    )
    if len(sl_instance) == 0:
        messages.error(request, "No location found!")
        return redirect(reverse('customer:service_locations'))
    sl_instance = sl_instance[0]
    if sl_instance.user != request.user:
        messages.error(request, 'You do not have permission to update this!')
        return redirect(reverse('customer:service_locations'))
    if request.method == 'POST':
        sl_form = ServiceLocationUpdateForm(request.POST, instance=sl_instance)
        if sl_form.is_valid():
            sl_form.save()
            messages.success(request, 'Service location details updated successfully')
            return redirect('customer:service_locations')
    sl_form = ServiceLocationUpdateForm(instance=sl_instance)
    return render(request, 'customer/update_location.html', {'sl_form': sl_form})


@login_required
def delete_service_location(request, location_id):
    location = get_object_or_404(ServiceLocation, pk=location_id, user=request.user)
    if location.user != request.user:
        messages.error(request, 'You do not have permission to delete this!')
        return redirect(reverse('customer:service_locations'))
    if request.method == 'POST':
        location.is_active = False
        location.save()
        messages.success(request, 'Service location is deleted.')
        return redirect('customer:service_locations')
    return render(request, 'customer/delete_service_location.html', {'location': location})


@login_required
def get_random_chart(request):
    labels = [f'Category {i}' for i in range(10)]
    return render(request, 'customer/show_piechart.html', context={
        'x_axis': 'Some random X axis',
        'y_axis': 'Some random Y axis',
        'labels': labels,
        'values': [random.randint(10, 100) for _ in range(10)],
        'data': [random.randint(10, 100) for _ in range(10)],
    })

customer/templates/customer/add_service_location.html
{% extends 'customer/base.html' %}
{% block content %}
  <h2>Add New Service Location</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {% for field in form %}
      <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
          <p class="help">{{ field.help_text }}</p>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit">Save Location</button>
  </form>
{% endblock %}

customer/templates/customer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Smart Home</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <!-- Font Awesome -->
    <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}" />
    {% block styles %}
    {% endblock styles %}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>
<body>
    <header>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'customer:home_page' %}">SmartHome
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:view_profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:service_locations' %}">Service Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:logout' %}">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% else %}
            <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'customer:home_page' %}">SmartHome
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:login' %}">Log In</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% endif %}
    </header>

    <br>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "success" %}
                    <div class="alert alert-dismissible alert-success">
                        <button type="submit" class="btn-close" onclick="dismissAlert(this)"></button>
                        <p class="mb-0">{{ message }}</p>
                    </div>
                {% elif message.tags == "error" %}
                    <div class="alert alert-dismissible alert-danger">
                        <button type="submit" class="btn-close" onclick="dismissAlert(this)"></button>
                        <p class="mb-0">{{ message }}</p>
                    </div>
                {% elif message.tags == "warning" %}
                    <div class="alert alert-dismissible alert-warning">
                        <button type="submit" class="btn-close" onclick="dismissAlert(this)"></button>
                        <p class="mb-0">{{ message }}</p>
                    </div>
                {% else %}
                    <div class="alert alert-dismissible alert-info">
                        <button type="submit" class="btn-close" onclick="dismissAlert(this)"></button>
                        <p class="mb-0">{{ message }}</p>
                    </div>
                {% endif %}
                <script>
                    function dismissAlert(button) {
                        button.parentElement.style.display = 'none';
                    }
                </script>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
        <script
            type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.umd.min.js">
        </script>
     </div>
</body>
</html>

customer/templates/customer/profile_view.html
{% extends 'customer/base.html' %}
{% load static %}
{% block content %}
<div class="container rounded bg-white">
    <div class="row">
        <div class="col-md-10">
            <div class="d-md-flex flex-column align-items-center">
                <img class="rounded-circle mt-5" 
                     width="150px"
                     src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"
                     alt="Stock Profile pic"
                >
                <span class="font-weight-bold">{{ first_name }} {{ last_name }}</span>
                <span class="text-black-50">{{ email }}</span>
            </div>
            <div class="mt-3 text-center">
                <a href="{% url 'customer:edit_profile' %}">
                    <button type="button" class="btn btn-outline-success">
                         <i class="fa fa-edit"></i> Edit profile
                    </button>
                </a>
                <br><br>
                <a href="{% url 'customer:service_locations' %}">
                    <button type="button" class="btn btn-outline-primary">
                         <i class="fas fa-house-user"></i> View Service Locations
                    </button>
                </a>
                <br><br>
                <a href="{% url 'device:show_user_eusage' %}">
                    <button type="button" class="btn btn-outline-info">
                         <i class="fas fa-chart-line"></i> View User Energy Usage
                    </button>
                </a>
                <br><br>
                <a href="{% url 'device:get_prices' %}">
                    <button type="button" class="btn btn-outline-info">
                         <i class="fas fa-chart-line"></i> View Zipcode Energy Prices 
                    </button>
                </a>
                <br><br>
                <a href="{% url 'customer:milestone_profile' %}">
                    <button type="button" class="btn btn-outline-danger">
                         <i class="fa fa-trash"></i> Delete profile
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{#        <div class="col-md-5 border-right">#}
{#            <div class="p-3 py-5">#}
{#                <div class="d-flex justify-content-between align-items-center mb-3">#}
{#                    <h4 class="text-right">Profile Settings</h4>#}
{#                </div>#}
{#                <div class="row mt-2">#}
{#                    <div class="col-md-6">#}
{#                        <label class="labels">First Name</label>#}
{#                        <input type="text" class="form-control" placeholder="First Name" value="">#}
{#                    </div>#}
{#                    <div class="col-md-6">#}
{#                        <label class="labels">Last Name</label>#}
{#                        <input type="text" class="form-control" value="" placeholder="Last Name">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="row mt-3">#}
{#                    <div class="col-md-12">#}
{#                        <label class="labels">Address Line 1</label>#}
{#                        <input type="text" class="form-control" placeholder="enter address line 1" value="">#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                        <label class="labels">Address Line 2</label>#}
{#                        <input type="text" class="form-control" placeholder="enter address line 2" value="">#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                        <label class="labels">Postcode</label>#}
{#                        <input type="text" class="form-control" placeholder="enter address line 2" value="">#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                        <label class="labels">State</label>#}
{#                        <input type="text" class="form-control" placeholder="enter address line 2" value="">#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                        <label class="labels">Area</label>#}
{#                        <input type="text" class="form-control" placeholder="enter address line 2" value="">#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                        <label class="labels">Email ID</label>#}
{#                        <input type="text" class="form-control" placeholder="enter email id" value="">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="row mt-3">#}
{#                    <div class="col-md-6">#}
{#                        <label class="labels">Country</label>#}
{#                        <input type="text" class="form-control" placeholder="country" value="">#}
{#                    </div>#}
{#                    <div class="col-md-6">#}
{#                        <label class="labels">State/Region</label>#}
{#                        <input type="text" class="form-control" value="" placeholder="state">#}
{#                    </div>#}
{#                </div>#}
{#                <div class="mt-5 text-center">#}
{#                    <button class="btn btn-primary profile-button" type="button">Save Profile</button>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        <div class="col-md-4">#}
{#            <div class="p-3 py-5">#}
{#                <div class="d-flex justify-content-between align-items-center experience">#}
{#                    <span>Add New Service Locations</span>#}
{#                    <span class="border px-3 p-1 add-experience"><i class="fa fa-plus"></i>&nbsp;Experience</span>#}
{#                </div><br>#}
{#                <div class="col-md-12">#}
{#                    <label class="labels">Experience in Designing</label>#}
{#                    <input type="text" class="form-control" placeholder="experience" value="">#}
{#                </div>#}
{#                <br>#}
{#                <div class="col-md-12">#}
{#                    <label class="labels">Additional Details</label>#}
{#                    <input type="text" class="form-control" placeholder="additional details" value="">#}
{#                </div>#}
{#            </div>#}
{#        </div>#}

customer/templates/customer/service_locations.html
{% extends 'customer/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col">
                <h1>Service Location Details</h1>
            </div>
        </div>
        <div class="row-gap-3 mt-3">
        <div class="col-md-5">
            <div class="card my-3">
                <img class="card-img-top" src="{% static 'customer/site_images/fancy-house-card.jpeg' %}"
                     alt="House image"
                     style="max-height: 250px"
                >
                <div class="card-body">
                    <div class="card-title">
                        <h3 class = "fw-bold">{{ location.apt_unit }} {{ location.street }}, {{ location.zipcode }}</h3>
                    </div>
                    <h5>Move-in-date: {{ location.move_in_date|date:"Y-m-d" }}</h5>
                    <h5><strong>Area:</strong> {{ location.area }}</h5>
                    <h5><strong>Bedrooms:</strong> {{ location.bedroom }}</h5>
                    <h5><strong>Occupants:</strong> {{ location.occupants }}</h5>
                    <br>
                    <div class="mb-1">
                        <a href="{% url 'device:show_sl_eusage' location_id=location.id %}"
                           class="btn btn-outline-info">View Energy Usage </a>
                    </div>
                    <div class="mb-1">
                        <a href="{% url 'device:get_device_pie' location.id %}"
                           class="btn btn-outline-info">View Pie Energy Usage</a>
                    </div>
                    <div class="mb-1">
                        <a href="{% url 'device:get_devices' location_id=location.id %}" class="btn btn-outline-primary">View Devices Installed</a>
                    </div>
                    <div class="mb-1">
                        <form action="{% url 'device:add_device' location_id=location.id %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-outline-primary" type="submit">Add Devices</button>
                        </form>
                    </div>
                    <div class="mb-1">
                        <a href="{% url 'customer:update_service_location' location_id=location.id %}"
                           class="btn btn-outline-info">Edit Service Location</a>
                    </div>
                    <div class="mb-1">
                        <a href="{% url 'customer:delete_service_location' location_id=location.id %}"
                           class="btn btn-outline-danger">Delete Service Location</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

customer/templates/customer/view_locations.html
{% extends 'customer/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        {% if locations %}
            <div class="row mt-3">
                <div class="col">
                    <h1>Your Service Locations</h1>
                </div>
            </div>
            <div class="row justify-content-start">
                {% for location in locations %}
                    <div class="card my-5">
                        <img class="card-img-top" src="{% static 'customer/site_images/smart_home_card.png' %}"
                             alt="Vacation image"
                             style="max-height: 200px; max-width: 100px">
                        <div class="card-body">
                            <h5 class="card-title ">Service Location</h5>
                            <p class="card-text fw-bold">
                                {{ location.apt_unit }} {{ location.street }}, {{ location.zipcode }}
                            </p>
                            <form action="{% url 'customer:detailed_service_locations' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="location_id" value="{{ location.id }}">
                                <button type="submit" class="btn btn-outline-info">
                                    View Detailed Service Locations
                                </button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
                 <div class="mt-5">
                    <a href="{% url 'customer:add_service_location' %}" class="btn btn-outline-primary">
                        Add New Service Location
                    </a>
                 </div>
            </div>
        {% else %}
            <div class="row mt-lg-5 mt-6">
                <img src="{% static 'customer/site_images/smart_home.jpeg' %}" style="max-height: 50%; max-width: 50%">
                <div class="col">
                    <h3>Please Add Service Locations to track electricity usages!</h3>
                    <div class="mt-5">
                        <a href="{% url 'customer:add_service_location' %}" class="btn btn-outline-success">
                            Add New Service Location
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}